<?php
/**
 * EndpointsInput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Spartera API Documentation
 *
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EndpointsInput Class Doc Comment
 *
 * @category Class
 * @description Input schema for creating Endpoint
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EndpointsInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'EndpointsInput';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'date_created' => '\DateTime',
        'last_updated' => '\DateTime',
        'user_id' => 'string',
        'company_id' => 'string',
        'connection_id' => 'string',
        'industry_id' => 'int',
        'auc_id' => 'int',
        'approval_status' => 'string',
        'approved_by_user_id' => 'string',
        'approved_at' => '\DateTime',
        'sell_in_marketplace' => 'bool',
        'price_credits' => 'int',
        'name' => 'string',
        'slug' => 'string',
        'description' => 'string',
        'source_schema_name' => 'string',
        'source_table_name' => 'string',
        'customer_name' => 'string',
        'price_usd' => 'float',
        'endpoint_schema' => 'object',
        'rate_limit_requests' => 'int',
        'rate_limit_period' => 'string',
        'rate_limit_granularity' => 'string',
        'access_method' => 'string',
        'access_whitelist' => 'object',
        'status' => 'string',
        'tags' => 'string',
        'last_accessed' => '\DateTime',
        'max_records_per_request' => 'int',
        'sample_response' => 'object',
        'active' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'date_created' => 'date-time',
        'last_updated' => 'date-time',
        'user_id' => null,
        'company_id' => null,
        'connection_id' => null,
        'industry_id' => 'int64',
        'auc_id' => 'int64',
        'approval_status' => null,
        'approved_by_user_id' => null,
        'approved_at' => 'date-time',
        'sell_in_marketplace' => null,
        'price_credits' => 'int64',
        'name' => null,
        'slug' => null,
        'description' => null,
        'source_schema_name' => null,
        'source_table_name' => null,
        'customer_name' => null,
        'price_usd' => 'float',
        'endpoint_schema' => null,
        'rate_limit_requests' => 'int64',
        'rate_limit_period' => null,
        'rate_limit_granularity' => null,
        'access_method' => null,
        'access_whitelist' => null,
        'status' => null,
        'tags' => null,
        'last_accessed' => 'date-time',
        'max_records_per_request' => 'int64',
        'sample_response' => null,
        'active' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'date_created' => false,
        'last_updated' => false,
        'user_id' => false,
        'company_id' => false,
        'connection_id' => false,
        'industry_id' => false,
        'auc_id' => false,
        'approval_status' => false,
        'approved_by_user_id' => false,
        'approved_at' => false,
        'sell_in_marketplace' => false,
        'price_credits' => false,
        'name' => false,
        'slug' => false,
        'description' => false,
        'source_schema_name' => false,
        'source_table_name' => false,
        'customer_name' => false,
        'price_usd' => false,
        'endpoint_schema' => false,
        'rate_limit_requests' => false,
        'rate_limit_period' => false,
        'rate_limit_granularity' => false,
        'access_method' => false,
        'access_whitelist' => false,
        'status' => false,
        'tags' => false,
        'last_accessed' => false,
        'max_records_per_request' => false,
        'sample_response' => false,
        'active' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'date_created' => 'date_created',
        'last_updated' => 'last_updated',
        'user_id' => 'user_id',
        'company_id' => 'company_id',
        'connection_id' => 'connection_id',
        'industry_id' => 'industry_id',
        'auc_id' => 'auc_id',
        'approval_status' => 'approval_status',
        'approved_by_user_id' => 'approved_by_user_id',
        'approved_at' => 'approved_at',
        'sell_in_marketplace' => 'sell_in_marketplace',
        'price_credits' => 'price_credits',
        'name' => 'name',
        'slug' => 'slug',
        'description' => 'description',
        'source_schema_name' => 'source_schema_name',
        'source_table_name' => 'source_table_name',
        'customer_name' => 'customer_name',
        'price_usd' => 'price_usd',
        'endpoint_schema' => 'endpoint_schema',
        'rate_limit_requests' => 'rate_limit_requests',
        'rate_limit_period' => 'rate_limit_period',
        'rate_limit_granularity' => 'rate_limit_granularity',
        'access_method' => 'access_method',
        'access_whitelist' => 'access_whitelist',
        'status' => 'status',
        'tags' => 'tags',
        'last_accessed' => 'last_accessed',
        'max_records_per_request' => 'max_records_per_request',
        'sample_response' => 'sample_response',
        'active' => 'active'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'date_created' => 'setDateCreated',
        'last_updated' => 'setLastUpdated',
        'user_id' => 'setUserId',
        'company_id' => 'setCompanyId',
        'connection_id' => 'setConnectionId',
        'industry_id' => 'setIndustryId',
        'auc_id' => 'setAucId',
        'approval_status' => 'setApprovalStatus',
        'approved_by_user_id' => 'setApprovedByUserId',
        'approved_at' => 'setApprovedAt',
        'sell_in_marketplace' => 'setSellInMarketplace',
        'price_credits' => 'setPriceCredits',
        'name' => 'setName',
        'slug' => 'setSlug',
        'description' => 'setDescription',
        'source_schema_name' => 'setSourceSchemaName',
        'source_table_name' => 'setSourceTableName',
        'customer_name' => 'setCustomerName',
        'price_usd' => 'setPriceUsd',
        'endpoint_schema' => 'setEndpointSchema',
        'rate_limit_requests' => 'setRateLimitRequests',
        'rate_limit_period' => 'setRateLimitPeriod',
        'rate_limit_granularity' => 'setRateLimitGranularity',
        'access_method' => 'setAccessMethod',
        'access_whitelist' => 'setAccessWhitelist',
        'status' => 'setStatus',
        'tags' => 'setTags',
        'last_accessed' => 'setLastAccessed',
        'max_records_per_request' => 'setMaxRecordsPerRequest',
        'sample_response' => 'setSampleResponse',
        'active' => 'setActive'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'date_created' => 'getDateCreated',
        'last_updated' => 'getLastUpdated',
        'user_id' => 'getUserId',
        'company_id' => 'getCompanyId',
        'connection_id' => 'getConnectionId',
        'industry_id' => 'getIndustryId',
        'auc_id' => 'getAucId',
        'approval_status' => 'getApprovalStatus',
        'approved_by_user_id' => 'getApprovedByUserId',
        'approved_at' => 'getApprovedAt',
        'sell_in_marketplace' => 'getSellInMarketplace',
        'price_credits' => 'getPriceCredits',
        'name' => 'getName',
        'slug' => 'getSlug',
        'description' => 'getDescription',
        'source_schema_name' => 'getSourceSchemaName',
        'source_table_name' => 'getSourceTableName',
        'customer_name' => 'getCustomerName',
        'price_usd' => 'getPriceUsd',
        'endpoint_schema' => 'getEndpointSchema',
        'rate_limit_requests' => 'getRateLimitRequests',
        'rate_limit_period' => 'getRateLimitPeriod',
        'rate_limit_granularity' => 'getRateLimitGranularity',
        'access_method' => 'getAccessMethod',
        'access_whitelist' => 'getAccessWhitelist',
        'status' => 'getStatus',
        'tags' => 'getTags',
        'last_accessed' => 'getLastAccessed',
        'max_records_per_request' => 'getMaxRecordsPerRequest',
        'sample_response' => 'getSampleResponse',
        'active' => 'getActive'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const APPROVAL_STATUS_PENDING = 'PENDING';
    public const APPROVAL_STATUS_APPROVED = 'APPROVED';
    public const APPROVAL_STATUS_REJECTED = 'REJECTED';
    public const APPROVAL_STATUS_NEEDS_REVISION = 'NEEDS_REVISION';
    public const RATE_LIMIT_PERIOD_SECOND = 'SECOND';
    public const RATE_LIMIT_PERIOD_MINUTE = 'MINUTE';
    public const RATE_LIMIT_PERIOD_HOUR = 'HOUR';
    public const RATE_LIMIT_PERIOD_DAY = 'DAY';
    public const RATE_LIMIT_GRANULARITY_USER = 'USER';
    public const RATE_LIMIT_GRANULARITY_COMPANY = 'COMPANY';
    public const RATE_LIMIT_GRANULARITY_IP = 'IP';
    public const RATE_LIMIT_GRANULARITY__GLOBAL = 'GLOBAL';
    public const ACCESS_METHOD_OPEN = 'OPEN';
    public const ACCESS_METHOD_API_KEY = 'API_KEY';
    public const ACCESS_METHOD_IP = 'IP';
    public const ACCESS_METHOD_EMAIL = 'EMAIL';
    public const ACCESS_METHOD_DOMAIN = 'DOMAIN';
    public const STATUS_ACTIVE = 'ACTIVE';
    public const STATUS_INACTIVE = 'INACTIVE';
    public const STATUS_DEPRECATED = 'DEPRECATED';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getApprovalStatusAllowableValues()
    {
        return [
            self::APPROVAL_STATUS_PENDING,
            self::APPROVAL_STATUS_APPROVED,
            self::APPROVAL_STATUS_REJECTED,
            self::APPROVAL_STATUS_NEEDS_REVISION,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRateLimitPeriodAllowableValues()
    {
        return [
            self::RATE_LIMIT_PERIOD_SECOND,
            self::RATE_LIMIT_PERIOD_MINUTE,
            self::RATE_LIMIT_PERIOD_HOUR,
            self::RATE_LIMIT_PERIOD_DAY,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRateLimitGranularityAllowableValues()
    {
        return [
            self::RATE_LIMIT_GRANULARITY_USER,
            self::RATE_LIMIT_GRANULARITY_COMPANY,
            self::RATE_LIMIT_GRANULARITY_IP,
            self::RATE_LIMIT_GRANULARITY__GLOBAL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAccessMethodAllowableValues()
    {
        return [
            self::ACCESS_METHOD_OPEN,
            self::ACCESS_METHOD_API_KEY,
            self::ACCESS_METHOD_IP,
            self::ACCESS_METHOD_EMAIL,
            self::ACCESS_METHOD_DOMAIN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_ACTIVE,
            self::STATUS_INACTIVE,
            self::STATUS_DEPRECATED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('date_created', $data ?? [], null);
        $this->setIfExists('last_updated', $data ?? [], null);
        $this->setIfExists('user_id', $data ?? [], null);
        $this->setIfExists('company_id', $data ?? [], null);
        $this->setIfExists('connection_id', $data ?? [], null);
        $this->setIfExists('industry_id', $data ?? [], null);
        $this->setIfExists('auc_id', $data ?? [], null);
        $this->setIfExists('approval_status', $data ?? [], null);
        $this->setIfExists('approved_by_user_id', $data ?? [], null);
        $this->setIfExists('approved_at', $data ?? [], null);
        $this->setIfExists('sell_in_marketplace', $data ?? [], null);
        $this->setIfExists('price_credits', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('slug', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('source_schema_name', $data ?? [], null);
        $this->setIfExists('source_table_name', $data ?? [], null);
        $this->setIfExists('customer_name', $data ?? [], null);
        $this->setIfExists('price_usd', $data ?? [], null);
        $this->setIfExists('endpoint_schema', $data ?? [], null);
        $this->setIfExists('rate_limit_requests', $data ?? [], null);
        $this->setIfExists('rate_limit_period', $data ?? [], null);
        $this->setIfExists('rate_limit_granularity', $data ?? [], null);
        $this->setIfExists('access_method', $data ?? [], null);
        $this->setIfExists('access_whitelist', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('last_accessed', $data ?? [], null);
        $this->setIfExists('max_records_per_request', $data ?? [], null);
        $this->setIfExists('sample_response', $data ?? [], null);
        $this->setIfExists('active', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['company_id'] === null) {
            $invalidProperties[] = "'company_id' can't be null";
        }
        if ($this->container['connection_id'] === null) {
            $invalidProperties[] = "'connection_id' can't be null";
        }
        $allowedValues = $this->getApprovalStatusAllowableValues();
        if (!is_null($this->container['approval_status']) && !in_array($this->container['approval_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'approval_status', must be one of '%s'",
                $this->container['approval_status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        $allowedValues = $this->getRateLimitPeriodAllowableValues();
        if (!is_null($this->container['rate_limit_period']) && !in_array($this->container['rate_limit_period'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'rate_limit_period', must be one of '%s'",
                $this->container['rate_limit_period'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getRateLimitGranularityAllowableValues();
        if (!is_null($this->container['rate_limit_granularity']) && !in_array($this->container['rate_limit_granularity'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'rate_limit_granularity', must be one of '%s'",
                $this->container['rate_limit_granularity'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getAccessMethodAllowableValues();
        if (!is_null($this->container['access_method']) && !in_array($this->container['access_method'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'access_method', must be one of '%s'",
                $this->container['access_method'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets date_created
     *
     * @return \DateTime|null
     */
    public function getDateCreated()
    {
        return $this->container['date_created'];
    }

    /**
     * Sets date_created
     *
     * @param \DateTime|null $date_created Required.
     *
     * @return self
     */
    public function setDateCreated($date_created)
    {
        if (is_null($date_created)) {
            throw new \InvalidArgumentException('non-nullable date_created cannot be null');
        }
        $this->container['date_created'] = $date_created;

        return $this;
    }

    /**
     * Gets last_updated
     *
     * @return \DateTime|null
     */
    public function getLastUpdated()
    {
        return $this->container['last_updated'];
    }

    /**
     * Sets last_updated
     *
     * @param \DateTime|null $last_updated Required.
     *
     * @return self
     */
    public function setLastUpdated($last_updated)
    {
        if (is_null($last_updated)) {
            throw new \InvalidArgumentException('non-nullable last_updated cannot be null');
        }
        $this->container['last_updated'] = $last_updated;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return string|null
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string|null $user_id User who created this endpoint
     *
     * @return self
     */
    public function setUserId($user_id)
    {
        if (is_null($user_id)) {
            throw new \InvalidArgumentException('non-nullable user_id cannot be null');
        }
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets company_id
     *
     * @return string
     */
    public function getCompanyId()
    {
        return $this->container['company_id'];
    }

    /**
     * Sets company_id
     *
     * @param string $company_id References companies.company_id — A Spartera seller or buyer company account. See GET /companies for valid values. Required.
     *
     * @return self
     */
    public function setCompanyId($company_id)
    {
        if (is_null($company_id)) {
            throw new \InvalidArgumentException('non-nullable company_id cannot be null');
        }
        $this->container['company_id'] = $company_id;

        return $this;
    }

    /**
     * Gets connection_id
     *
     * @return string
     */
    public function getConnectionId()
    {
        return $this->container['connection_id'];
    }

    /**
     * Sets connection_id
     *
     * @param string $connection_id Connection to the data source
     *
     * @return self
     */
    public function setConnectionId($connection_id)
    {
        if (is_null($connection_id)) {
            throw new \InvalidArgumentException('non-nullable connection_id cannot be null');
        }
        $this->container['connection_id'] = $connection_id;

        return $this;
    }

    /**
     * Gets industry_id
     *
     * @return int|null
     */
    public function getIndustryId()
    {
        return $this->container['industry_id'];
    }

    /**
     * Sets industry_id
     *
     * @param int|null $industry_id Industry / category for marketplace discovery
     *
     * @return self
     */
    public function setIndustryId($industry_id)
    {
        if (is_null($industry_id)) {
            throw new \InvalidArgumentException('non-nullable industry_id cannot be null');
        }
        $this->container['industry_id'] = $industry_id;

        return $this;
    }

    /**
     * Gets auc_id
     *
     * @return int|null
     */
    public function getAucId()
    {
        return $this->container['auc_id'];
    }

    /**
     * Sets auc_id
     *
     * @param int|null $auc_id Primary use case for marketplace discovery
     *
     * @return self
     */
    public function setAucId($auc_id)
    {
        if (is_null($auc_id)) {
            throw new \InvalidArgumentException('non-nullable auc_id cannot be null');
        }
        $this->container['auc_id'] = $auc_id;

        return $this;
    }

    /**
     * Gets approval_status
     *
     * @return string|null
     */
    public function getApprovalStatus()
    {
        return $this->container['approval_status'];
    }

    /**
     * Sets approval_status
     *
     * @param string|null $approval_status Approval status before marketplace publication
     *
     * @return self
     */
    public function setApprovalStatus($approval_status)
    {
        if (is_null($approval_status)) {
            throw new \InvalidArgumentException('non-nullable approval_status cannot be null');
        }
        $allowedValues = $this->getApprovalStatusAllowableValues();
        if (!in_array($approval_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'approval_status', must be one of '%s'",
                    $approval_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['approval_status'] = $approval_status;

        return $this;
    }

    /**
     * Gets approved_by_user_id
     *
     * @return string|null
     */
    public function getApprovedByUserId()
    {
        return $this->container['approved_by_user_id'];
    }

    /**
     * Sets approved_by_user_id
     *
     * @param string|null $approved_by_user_id User who approved this endpoint for marketplace
     *
     * @return self
     */
    public function setApprovedByUserId($approved_by_user_id)
    {
        if (is_null($approved_by_user_id)) {
            throw new \InvalidArgumentException('non-nullable approved_by_user_id cannot be null');
        }
        $this->container['approved_by_user_id'] = $approved_by_user_id;

        return $this;
    }

    /**
     * Gets approved_at
     *
     * @return \DateTime|null
     */
    public function getApprovedAt()
    {
        return $this->container['approved_at'];
    }

    /**
     * Sets approved_at
     *
     * @param \DateTime|null $approved_at Timestamp of marketplace approval
     *
     * @return self
     */
    public function setApprovedAt($approved_at)
    {
        if (is_null($approved_at)) {
            throw new \InvalidArgumentException('non-nullable approved_at cannot be null');
        }
        $this->container['approved_at'] = $approved_at;

        return $this;
    }

    /**
     * Gets sell_in_marketplace
     *
     * @return bool|null
     */
    public function getSellInMarketplace()
    {
        return $this->container['sell_in_marketplace'];
    }

    /**
     * Sets sell_in_marketplace
     *
     * @param bool|null $sell_in_marketplace Whether this endpoint appears in the public marketplace
     *
     * @return self
     */
    public function setSellInMarketplace($sell_in_marketplace)
    {
        if (is_null($sell_in_marketplace)) {
            throw new \InvalidArgumentException('non-nullable sell_in_marketplace cannot be null');
        }
        $this->container['sell_in_marketplace'] = $sell_in_marketplace;

        return $this;
    }

    /**
     * Gets price_credits
     *
     * @return int|null
     */
    public function getPriceCredits()
    {
        return $this->container['price_credits'];
    }

    /**
     * Sets price_credits
     *
     * @param int|null $price_credits Credits deducted from the buyer's pool per successful (200 OK) request. Same credit pool as assets. price_usd kept for billing records / dashboards.
     *
     * @return self
     */
    public function setPriceCredits($price_credits)
    {
        if (is_null($price_credits)) {
            throw new \InvalidArgumentException('non-nullable price_credits cannot be null');
        }
        $this->container['price_credits'] = $price_credits;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Human-readable name for the endpoint
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets slug
     *
     * @return string|null
     */
    public function getSlug()
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug
     *
     * @param string|null $slug Human-readable, URL-safe slug derived from name at creation time. e.g. 'NFL Live Moneyline & Spread Odds' → 'nfl-live-moneyline-spread-odds'. Never changes after creation. Unique within company (DB constraint). Creation fails with 409 if a duplicate name exists in the same company.
     *
     * @return self
     */
    public function setSlug($slug)
    {
        if (is_null($slug)) {
            throw new \InvalidArgumentException('non-nullable slug cannot be null');
        }
        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Description of what this endpoint provides
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets source_schema_name
     *
     * @return string|null
     */
    public function getSourceSchemaName()
    {
        return $this->container['source_schema_name'];
    }

    /**
     * Sets source_schema_name
     *
     * @param string|null $source_schema_name Schema/database name where the table resides
     *
     * @return self
     */
    public function setSourceSchemaName($source_schema_name)
    {
        if (is_null($source_schema_name)) {
            throw new \InvalidArgumentException('non-nullable source_schema_name cannot be null');
        }
        $this->container['source_schema_name'] = $source_schema_name;

        return $this;
    }

    /**
     * Gets source_table_name
     *
     * @return string|null
     */
    public function getSourceTableName()
    {
        return $this->container['source_table_name'];
    }

    /**
     * Sets source_table_name
     *
     * @param string|null $source_table_name Table name to query from
     *
     * @return self
     */
    public function setSourceTableName($source_table_name)
    {
        if (is_null($source_table_name)) {
            throw new \InvalidArgumentException('non-nullable source_table_name cannot be null');
        }
        $this->container['source_table_name'] = $source_table_name;

        return $this;
    }

    /**
     * Gets customer_name
     *
     * @return string|null
     */
    public function getCustomerName()
    {
        return $this->container['customer_name'];
    }

    /**
     * Sets customer_name
     *
     * @param string|null $customer_name Named customer for B2B deals (marketplace uses price_credits instead)
     *
     * @return self
     */
    public function setCustomerName($customer_name)
    {
        if (is_null($customer_name)) {
            throw new \InvalidArgumentException('non-nullable customer_name cannot be null');
        }
        $this->container['customer_name'] = $customer_name;

        return $this;
    }

    /**
     * Gets price_usd
     *
     * @return float|null
     */
    public function getPriceUsd()
    {
        return $this->container['price_usd'];
    }

    /**
     * Sets price_usd
     *
     * @param float|null $price_usd USD reference price for billing records and seller dashboards
     *
     * @return self
     */
    public function setPriceUsd($price_usd)
    {
        if (is_null($price_usd)) {
            throw new \InvalidArgumentException('non-nullable price_usd cannot be null');
        }
        $this->container['price_usd'] = $price_usd;

        return $this;
    }

    /**
     * Gets endpoint_schema
     *
     * @return object|null
     */
    public function getEndpointSchema()
    {
        return $this->container['endpoint_schema'];
    }

    /**
     * Sets endpoint_schema
     *
     * @param object|null $endpoint_schema Column configurations including aggregations, filters, and visibility. Format: {columns: [{name, type, aggregation, filter, is_hidden, alias, ...}]}. This is the source of truth — SQL is generated at runtime from this configuration.
     *
     * @return self
     */
    public function setEndpointSchema($endpoint_schema)
    {
        if (is_null($endpoint_schema)) {
            throw new \InvalidArgumentException('non-nullable endpoint_schema cannot be null');
        }
        $this->container['endpoint_schema'] = $endpoint_schema;

        return $this;
    }

    /**
     * Gets rate_limit_requests
     *
     * @return int|null
     */
    public function getRateLimitRequests()
    {
        return $this->container['rate_limit_requests'];
    }

    /**
     * Sets rate_limit_requests
     *
     * @param int|null $rate_limit_requests Number of requests allowed per rate_limit_period
     *
     * @return self
     */
    public function setRateLimitRequests($rate_limit_requests)
    {
        if (is_null($rate_limit_requests)) {
            throw new \InvalidArgumentException('non-nullable rate_limit_requests cannot be null');
        }
        $this->container['rate_limit_requests'] = $rate_limit_requests;

        return $this;
    }

    /**
     * Gets rate_limit_period
     *
     * @return string|null
     */
    public function getRateLimitPeriod()
    {
        return $this->container['rate_limit_period'];
    }

    /**
     * Sets rate_limit_period
     *
     * @param string|null $rate_limit_period Time period for rate limiting (HOUR, DAY, MONTH)
     *
     * @return self
     */
    public function setRateLimitPeriod($rate_limit_period)
    {
        if (is_null($rate_limit_period)) {
            throw new \InvalidArgumentException('non-nullable rate_limit_period cannot be null');
        }
        $allowedValues = $this->getRateLimitPeriodAllowableValues();
        if (!in_array($rate_limit_period, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'rate_limit_period', must be one of '%s'",
                    $rate_limit_period,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['rate_limit_period'] = $rate_limit_period;

        return $this;
    }

    /**
     * Gets rate_limit_granularity
     *
     * @return string|null
     */
    public function getRateLimitGranularity()
    {
        return $this->container['rate_limit_granularity'];
    }

    /**
     * Sets rate_limit_granularity
     *
     * @param string|null $rate_limit_granularity How to group rate limits (IP, USER, COMPANY, API_KEY, GLOBAL)
     *
     * @return self
     */
    public function setRateLimitGranularity($rate_limit_granularity)
    {
        if (is_null($rate_limit_granularity)) {
            throw new \InvalidArgumentException('non-nullable rate_limit_granularity cannot be null');
        }
        $allowedValues = $this->getRateLimitGranularityAllowableValues();
        if (!in_array($rate_limit_granularity, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'rate_limit_granularity', must be one of '%s'",
                    $rate_limit_granularity,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['rate_limit_granularity'] = $rate_limit_granularity;

        return $this;
    }

    /**
     * Gets access_method
     *
     * @return string|null
     */
    public function getAccessMethod()
    {
        return $this->container['access_method'];
    }

    /**
     * Sets access_method
     *
     * @param string|null $access_method Access control method (OPEN, API_KEY, IP, EMAIL, DOMAIN)
     *
     * @return self
     */
    public function setAccessMethod($access_method)
    {
        if (is_null($access_method)) {
            throw new \InvalidArgumentException('non-nullable access_method cannot be null');
        }
        $allowedValues = $this->getAccessMethodAllowableValues();
        if (!in_array($access_method, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'access_method', must be one of '%s'",
                    $access_method,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['access_method'] = $access_method;

        return $this;
    }

    /**
     * Gets access_whitelist
     *
     * @return object|null
     */
    public function getAccessWhitelist()
    {
        return $this->container['access_whitelist'];
    }

    /**
     * Sets access_whitelist
     *
     * @param object|null $access_whitelist List of allowed IPs, emails, or domains based on access_method. Format: {type: 'ip'|'email'|'domain', values: ['192.168.1.1', ...]}
     *
     * @return self
     */
    public function setAccessWhitelist($access_whitelist)
    {
        if (is_null($access_whitelist)) {
            throw new \InvalidArgumentException('non-nullable access_whitelist cannot be null');
        }
        $this->container['access_whitelist'] = $access_whitelist;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status Current status of the endpoint (ACTIVE, INACTIVE, DEPRECATED)
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string|null $tags Comma-separated tags for organizing endpoints
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets last_accessed
     *
     * @return \DateTime|null
     */
    public function getLastAccessed()
    {
        return $this->container['last_accessed'];
    }

    /**
     * Sets last_accessed
     *
     * @param \DateTime|null $last_accessed When this endpoint was last called
     *
     * @return self
     */
    public function setLastAccessed($last_accessed)
    {
        if (is_null($last_accessed)) {
            throw new \InvalidArgumentException('non-nullable last_accessed cannot be null');
        }
        $this->container['last_accessed'] = $last_accessed;

        return $this;
    }

    /**
     * Gets max_records_per_request
     *
     * @return int|null
     */
    public function getMaxRecordsPerRequest()
    {
        return $this->container['max_records_per_request'];
    }

    /**
     * Sets max_records_per_request
     *
     * @param int|null $max_records_per_request Seller-enforced row cap per request. Buyers cannot exceed this. Default 1000.
     *
     * @return self
     */
    public function setMaxRecordsPerRequest($max_records_per_request)
    {
        if (is_null($max_records_per_request)) {
            throw new \InvalidArgumentException('non-nullable max_records_per_request cannot be null');
        }
        $this->container['max_records_per_request'] = $max_records_per_request;

        return $this;
    }

    /**
     * Gets sample_response
     *
     * @return object|null
     */
    public function getSampleResponse()
    {
        return $this->container['sample_response'];
    }

    /**
     * Sets sample_response
     *
     * @param object|null $sample_response Last successful {spartera, request, response} envelope. Saved on each successful marketplace run. Displayed as preview on product page load.
     *
     * @return self
     */
    public function setSampleResponse($sample_response)
    {
        if (is_null($sample_response)) {
            throw new \InvalidArgumentException('non-nullable sample_response cannot be null');
        }
        $this->container['sample_response'] = $sample_response;

        return $this;
    }

    /**
     * Gets active
     *
     * @return bool|null
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param bool|null $active Required.
     *
     * @return self
     */
    public function setActive($active)
    {
        if (is_null($active)) {
            throw new \InvalidArgumentException('non-nullable active cannot be null');
        }
        $this->container['active'] = $active;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


