<?php
/**
 * StorageEngines
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Spartera API Documentation
 *
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * StorageEngines Class Doc Comment
 *
 * @category Class
 * @description Fact table of all the different storage engines we support
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class StorageEngines implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'StorageEngines';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'date_created' => '\DateTime',
        'last_updated' => '\DateTime',
        'engine_id' => 'int',
        'provider_id' => 'int',
        'service_name' => 'string',
        'engine_type' => 'string',
        'integration_complete' => 'bool',
        'test_func_complete' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'date_created' => 'date-time',
        'last_updated' => 'date-time',
        'engine_id' => 'int64',
        'provider_id' => 'int64',
        'service_name' => null,
        'engine_type' => null,
        'integration_complete' => null,
        'test_func_complete' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'date_created' => false,
        'last_updated' => false,
        'engine_id' => false,
        'provider_id' => false,
        'service_name' => false,
        'engine_type' => false,
        'integration_complete' => false,
        'test_func_complete' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'date_created' => 'date_created',
        'last_updated' => 'last_updated',
        'engine_id' => 'engine_id',
        'provider_id' => 'provider_id',
        'service_name' => 'service_name',
        'engine_type' => 'engine_type',
        'integration_complete' => 'integration_complete',
        'test_func_complete' => 'test_func_complete'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'date_created' => 'setDateCreated',
        'last_updated' => 'setLastUpdated',
        'engine_id' => 'setEngineId',
        'provider_id' => 'setProviderId',
        'service_name' => 'setServiceName',
        'engine_type' => 'setEngineType',
        'integration_complete' => 'setIntegrationComplete',
        'test_func_complete' => 'setTestFuncComplete'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'date_created' => 'getDateCreated',
        'last_updated' => 'getLastUpdated',
        'engine_id' => 'getEngineId',
        'provider_id' => 'getProviderId',
        'service_name' => 'getServiceName',
        'engine_type' => 'getEngineType',
        'integration_complete' => 'getIntegrationComplete',
        'test_func_complete' => 'getTestFuncComplete'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ENGINE_TYPE_EDW = 'EDW';
    public const ENGINE_TYPE_LLM = 'LLM';
    public const ENGINE_TYPE_RDBMS = 'RDBMS';
    public const ENGINE_TYPE_OBJ = 'OBJ';
    public const ENGINE_TYPE_API_MODEL = 'API_MODEL';
    public const ENGINE_TYPE_EXTERNAL_API = 'EXTERNAL_API';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEngineTypeAllowableValues()
    {
        return [
            self::ENGINE_TYPE_EDW,
            self::ENGINE_TYPE_LLM,
            self::ENGINE_TYPE_RDBMS,
            self::ENGINE_TYPE_OBJ,
            self::ENGINE_TYPE_API_MODEL,
            self::ENGINE_TYPE_EXTERNAL_API,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('date_created', $data ?? [], null);
        $this->setIfExists('last_updated', $data ?? [], null);
        $this->setIfExists('engine_id', $data ?? [], null);
        $this->setIfExists('provider_id', $data ?? [], null);
        $this->setIfExists('service_name', $data ?? [], null);
        $this->setIfExists('engine_type', $data ?? [], null);
        $this->setIfExists('integration_complete', $data ?? [], null);
        $this->setIfExists('test_func_complete', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['provider_id'] === null) {
            $invalidProperties[] = "'provider_id' can't be null";
        }
        if ($this->container['service_name'] === null) {
            $invalidProperties[] = "'service_name' can't be null";
        }
        if ($this->container['engine_type'] === null) {
            $invalidProperties[] = "'engine_type' can't be null";
        }
        $allowedValues = $this->getEngineTypeAllowableValues();
        if (!is_null($this->container['engine_type']) && !in_array($this->container['engine_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'engine_type', must be one of '%s'",
                $this->container['engine_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets date_created
     *
     * @return \DateTime|null
     */
    public function getDateCreated()
    {
        return $this->container['date_created'];
    }

    /**
     * Sets date_created
     *
     * @param \DateTime|null $date_created Optional.
     *
     * @return self
     */
    public function setDateCreated($date_created)
    {
        if (is_null($date_created)) {
            throw new \InvalidArgumentException('non-nullable date_created cannot be null');
        }
        $this->container['date_created'] = $date_created;

        return $this;
    }

    /**
     * Gets last_updated
     *
     * @return \DateTime|null
     */
    public function getLastUpdated()
    {
        return $this->container['last_updated'];
    }

    /**
     * Sets last_updated
     *
     * @param \DateTime|null $last_updated Optional.
     *
     * @return self
     */
    public function setLastUpdated($last_updated)
    {
        if (is_null($last_updated)) {
            throw new \InvalidArgumentException('non-nullable last_updated cannot be null');
        }
        $this->container['last_updated'] = $last_updated;

        return $this;
    }

    /**
     * Gets engine_id
     *
     * @return int|null
     */
    public function getEngineId()
    {
        return $this->container['engine_id'];
    }

    /**
     * Sets engine_id
     *
     * @param int|null $engine_id Unique identifier.
     *
     * @return self
     */
    public function setEngineId($engine_id)
    {
        if (is_null($engine_id)) {
            throw new \InvalidArgumentException('non-nullable engine_id cannot be null');
        }
        $this->container['engine_id'] = $engine_id;

        return $this;
    }

    /**
     * Gets provider_id
     *
     * @return int
     */
    public function getProviderId()
    {
        return $this->container['provider_id'];
    }

    /**
     * Sets provider_id
     *
     * @param int $provider_id References cloud_providers.provider_id — Supported cloud platforms and database engines available for connections. See GET /cloud_providers for valid values. Required.
     *
     * @return self
     */
    public function setProviderId($provider_id)
    {
        if (is_null($provider_id)) {
            throw new \InvalidArgumentException('non-nullable provider_id cannot be null');
        }
        $this->container['provider_id'] = $provider_id;

        return $this;
    }

    /**
     * Gets service_name
     *
     * @return string
     */
    public function getServiceName()
    {
        return $this->container['service_name'];
    }

    /**
     * Sets service_name
     *
     * @param string $service_name Required.
     *
     * @return self
     */
    public function setServiceName($service_name)
    {
        if (is_null($service_name)) {
            throw new \InvalidArgumentException('non-nullable service_name cannot be null');
        }
        $this->container['service_name'] = $service_name;

        return $this;
    }

    /**
     * Gets engine_type
     *
     * @return string
     */
    public function getEngineType()
    {
        return $this->container['engine_type'];
    }

    /**
     * Sets engine_type
     *
     * @param string $engine_type Required. One of: EDW, LLM, RDBMS, OBJ, API_MODEL, … (6 total).
     *
     * @return self
     */
    public function setEngineType($engine_type)
    {
        if (is_null($engine_type)) {
            throw new \InvalidArgumentException('non-nullable engine_type cannot be null');
        }
        $allowedValues = $this->getEngineTypeAllowableValues();
        if (!in_array($engine_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'engine_type', must be one of '%s'",
                    $engine_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['engine_type'] = $engine_type;

        return $this;
    }

    /**
     * Gets integration_complete
     *
     * @return bool|null
     */
    public function getIntegrationComplete()
    {
        return $this->container['integration_complete'];
    }

    /**
     * Sets integration_complete
     *
     * @param bool|null $integration_complete Optional.
     *
     * @return self
     */
    public function setIntegrationComplete($integration_complete)
    {
        if (is_null($integration_complete)) {
            throw new \InvalidArgumentException('non-nullable integration_complete cannot be null');
        }
        $this->container['integration_complete'] = $integration_complete;

        return $this;
    }

    /**
     * Gets test_func_complete
     *
     * @return bool|null
     */
    public function getTestFuncComplete()
    {
        return $this->container['test_func_complete'];
    }

    /**
     * Sets test_func_complete
     *
     * @param bool|null $test_func_complete Optional.
     *
     * @return self
     */
    public function setTestFuncComplete($test_func_complete)
    {
        if (is_null($test_func_complete)) {
            throw new \InvalidArgumentException('non-nullable test_func_complete cannot be null');
        }
        $this->container['test_func_complete'] = $test_func_complete;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


