<?php
/**
 * AlertsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  SparteraApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Spartera API Documentation
 *
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@spartera.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SparteraApiSdk\Test\Api;

use \SparteraApiSdk\Configuration;
use \SparteraApiSdk\ApiException;
use \SparteraApiSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AlertsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SparteraApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AlertsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for companiesCompanyIdUsersUserIdAlertsAlertIdDelete
     *
     * Delete single alert by ID.
     *
     */
    public function testCompaniesCompanyIdUsersUserIdAlertsAlertIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdUsersUserIdAlertsAlertIdGet
     *
     * Get single alert by ID.
     *
     */
    public function testCompaniesCompanyIdUsersUserIdAlertsAlertIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdUsersUserIdAlertsAlertIdPatch
     *
     * Update an existing alert by ID.
     *
     */
    public function testCompaniesCompanyIdUsersUserIdAlertsAlertIdPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdUsersUserIdAlertsAssetAssetIdAllGet
     *
     * Get all alerts for a specific asset (from all users)     This would typically be restricted to asset owners or admins.
     *
     */
    public function testCompaniesCompanyIdUsersUserIdAlertsAssetAssetIdAllGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdUsersUserIdAlertsAssetAssetIdGet
     *
     * Get all alerts for a specific asset by the specified user     Useful for checking if user already has an alert set up for an asset.
     *
     */
    public function testCompaniesCompanyIdUsersUserIdAlertsAssetAssetIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdUsersUserIdAlertsGet
     *
     * Get a list of all alerts for a specific user.
     *
     */
    public function testCompaniesCompanyIdUsersUserIdAlertsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdUsersUserIdAlertsPost
     *
     * POST /companies/{company_id}/users/{user_id}/alerts.
     *
     */
    public function testCompaniesCompanyIdUsersUserIdAlertsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
