<?php
/**
 * APIKeysApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Spartera API Documentation
 *
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * APIKeysApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class APIKeysApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createApiKeys
     *
     * Create single API key.     Returns the actual sk_ key (only time it's exposed) and api_key_id for future operations..
     *
     */
    public function testCreateApiKeys()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createApiKeysApiKeysRevoke
     *
     * Explicitly revoke an API key with reason tracking.     This is different from delete as it includes revocation metadata..
     *
     */
    public function testCreateApiKeysApiKeysRevoke()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteApiKeys
     *
     * Delete (deactivate) single API key by api_key_id.     Uses the api_key_id returned during creation for clean identification.     Fixed to use correct primary key lookup..
     *
     */
    public function testDeleteApiKeys()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApiKeysById
     *
     * Get single API key by ID.     Returns masked API key for security (sk_****1234)..
     *
     */
    public function testGetApiKeysById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApiKeysByIdApiKeysStats
     *
     * Get usage statistics for a specific API key.     Returns usage count, last used date, failed attempts, etc..
     *
     */
    public function testGetApiKeysByIdApiKeysStats()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listApiKeys
     *
     * Get all API keys for a company.     Returns masked API keys for security (sk_****1234)..
     *
     */
    public function testListApiKeys()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateApiKeys
     *
     * Update an existing API key by ID.     Can update metadata like name, expiration, rate limits, etc.     Cannot update the actual key value (for security)..
     *
     */
    public function testUpdateApiKeys()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
