<?php
/**
 * APIKeysApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  SparteraApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Spartera API Documentation
 *
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.24.0
 * Contact: support@spartera.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SparteraApiSdk\Test\Api;

use \SparteraApiSdk\Configuration;
use \SparteraApiSdk\ApiException;
use \SparteraApiSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * APIKeysApiTest Class Doc Comment
 *
 * @category Class
 * @package  SparteraApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class APIKeysApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for companiesCompanyIdApiKeysApiKeyIdDelete
     *
     * Delete (deactivate) single API key by api_key_id.     Uses the api_key_id returned during creation for clean identification.     Fixed to use correct primary key lookup..
     *
     */
    public function testCompaniesCompanyIdApiKeysApiKeyIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdApiKeysApiKeyIdGet
     *
     * Get single API key by ID.     Returns masked API key for security (sk_****1234)..
     *
     */
    public function testCompaniesCompanyIdApiKeysApiKeyIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdApiKeysApiKeyIdPatch
     *
     * Update an existing API key by ID.     Can update metadata like name, expiration, rate limits, etc.     Cannot update the actual key value (for security)..
     *
     */
    public function testCompaniesCompanyIdApiKeysApiKeyIdPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdApiKeysApiKeyIdRevokePost
     *
     * Explicitly revoke an API key with reason tracking.     This is different from delete as it includes revocation metadata..
     *
     */
    public function testCompaniesCompanyIdApiKeysApiKeyIdRevokePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdApiKeysApiKeyIdStatsGet
     *
     * Get usage statistics for a specific API key.     Returns usage count, last used date, failed attempts, etc..
     *
     */
    public function testCompaniesCompanyIdApiKeysApiKeyIdStatsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdApiKeysGet
     *
     * Get all API keys for a company.     Returns masked API keys for security (sk_****1234)..
     *
     */
    public function testCompaniesCompanyIdApiKeysGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdApiKeysPost
     *
     * Create single API key.     Returns the actual sk_ key (only time it's exposed) and api_key_id for future operations..
     *
     */
    public function testCompaniesCompanyIdApiKeysPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
