<?php
/**
 * CompaniesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  SparteraApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Spartera API Documentation
 *
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@spartera.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SparteraApiSdk\Test\Api;

use \SparteraApiSdk\Configuration;
use \SparteraApiSdk\ApiException;
use \SparteraApiSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CompaniesApiTest Class Doc Comment
 *
 * @category Class
 * @package  SparteraApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CompaniesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for companiesCompanyIdAnalyticsAssetsGet
     *
     * Get asset performance analytics     Query params: start_date, end_date, limit, sort_by, include.
     *
     */
    public function testCompaniesCompanyIdAnalyticsAssetsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdAnalyticsCustomersGet
     *
     * Get customer analytics including growth and segmentation     Query params: start_date, end_date, group_by, segment_by.
     *
     */
    public function testCompaniesCompanyIdAnalyticsCustomersGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdAnalyticsDashboardGet
     *
     * Get comprehensive dashboard analytics for seller dashboard     Includes all metrics needed for dashboard charts in one call     Query params: start_date, end_date, period (day/week/month/quarter).
     *
     */
    public function testCompaniesCompanyIdAnalyticsDashboardGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdAnalyticsSalesGet
     *
     * Get sales over time analytics     Query params: start_date, end_date, group_by (day/week/month/quarter), metrics.
     *
     */
    public function testCompaniesCompanyIdAnalyticsSalesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdGet
     *
     * Get details of the requestor's own company.
     *
     */
    public function testCompaniesCompanyIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdObjectsGet
     *
     * Get all objects (connections, assets) of a single company.
     *
     */
    public function testCompaniesCompanyIdObjectsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdPatch
     *
     * Update an existing company by ID.
     *
     */
    public function testCompaniesCompanyIdPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdRequestsPlanGet
     *
     * Get the total number of requests allocated in the company's current subscription plan..
     *
     */
    public function testCompaniesCompanyIdRequestsPlanGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdRequestsUsageGet
     *
     * Get company request usage data for a specific month. Returns JSON metrics by default or CSV logs when download parameter is included..
     *
     */
    public function testCompaniesCompanyIdRequestsUsageGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
