<?php
/**
 * ConnectionsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  SparteraApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Spartera API Documentation
 *
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@spartera.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SparteraApiSdk\Test\Api;

use \SparteraApiSdk\Configuration;
use \SparteraApiSdk\ApiException;
use \SparteraApiSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ConnectionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SparteraApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConnectionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdDelete
     *
     * Delete single connection by ID.
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdGet
     *
     * Get single connection by ID.
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdInfoschemaGet
     *
     * Retrieve the information schema for the specified connection.
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdInfoschemaGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdPatch
     *
     * Update an existing connection by ID.
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdTestGet
     *
     * Verify the specified connection to ensure it is functioning correctly.
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdTestGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsGet
     *
     * Get all connections for a specific company.
     *
     */
    public function testCompaniesCompanyIdConnectionsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsPost
     *
     * Create a new connection by ID.
     *
     */
    public function testCompaniesCompanyIdConnectionsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
